#!/usr/bin/env python3
"""
Génère ar.html et en.html à partir de index.html (français, source de vérité).

Une seule structure, trois pages. Modifiez index.html, ajoutez la traduction
ici si la phrase est nouvelle, relancez :  python3 build-langs.py

Les chaînes sont remplacées de la plus longue à la plus courte, via des jetons
intermédiaires, pour qu'une phrase courte ne puisse jamais corrompre une phrase
longue qui la contient.
"""
import pathlib
import re
import sys

SRC = pathlib.Path(__file__).parent / "index.html"

# (français, anglais, arabe)
T = [
    # ── six semaines ────────────────────────────────────────────────────
    ("Six semaines", "Six weeks", "ستة أسابيع"),
    ("Choisir la langue", "Choose a language", "اختر اللغة"),
    ("Choisir la semaine", "Choose the week", "اختر الأسبوع"),
    ("Voir les six semaines", "Play the six weeks", "شاهد الأسابيع الستة"),
    ("Arrêter", "Stop", "إيقاف"),
    ("Jour 0", "Day 0", "اليوم 0"),
    ("Sem. 1", "Wk 1", "أسبوع 1"),
    ("Sem. 2", "Wk 2", "أسبوع 2"),
    ("Sem. 3", "Wk 3", "أسبوع 3"),
    ("Sem. 4", "Wk 4", "أسبوع 4"),
    ("Sem. 5", "Wk 5", "أسبوع 5"),
    ("Sem. 6", "Wk 6", "أسبوع 6"),
    ("heure du réveil", "time of waking", "ساعة الاستيقاظ"),
    ("La même chambre, semaine après semaine : la nuit s'allonge, l'heure du réveil recule, la personne se redresse.",
     "The same room, week after week: the night lengthens, waking moves later, the person straightens up.",
     "الغرفة نفسها، أسبوعًا بعد أسبوع: تطول الليلة، ويتأخر موعد الاستيقاظ، ويستقيم الشخص."),
    ("Le premier signe de guérison n'est ni l'humeur ni la motivation : c'est la nuit. Voici, semaine par semaine, ce qui se passe réellement — la même chambre, le même lit, la même personne, à six semaines d'intervalle.",
     "The first sign of recovery is neither mood nor motivation: it is the night. Here, week by week, is what actually happens — the same room, the same bed, the same person, six weeks apart.",
     "أول علامة على التعافي ليست المزاج ولا الدافعية: إنها الليل. وهذا، أسبوعًا بأسبوع، ما يحدث فعلًا — الغرفة نفسها، والسرير نفسه، والشخص نفسه، بفارق ستة أسابيع."),
    ("La dernière nuit avant l'entrée", "The last night before admission", "الليلة الأخيرة قبل الدخول"),
    ("Trois heures de sommeil, coupées en morceaux. Le réveil de 3 h du matin est le plus dur : c'est l'heure où le manque se réveille avant vous, et où l'on reprend souvent pour pouvoir se rendormir.",
     "Three hours of sleep, cut into pieces. The 3 a.m. waking is the hardest: it is the hour when withdrawal wakes before you do, and when people often use again just to get back to sleep.",
     "ثلاث ساعات من النوم، مقطّعة. الاستيقاظ في الثالثة فجرًا هو الأصعب: إنها الساعة التي يستيقظ فيها الانسحاب قبلك، وغالبًا ما يعود المرء إلى التعاطي لينام من جديد."),
    ("Le corps se calme", "The body settles", "الجسد يهدأ"),
    ("Le sevrage médicalisé est passé. Les tremblements ont cessé, la tension et le pouls redescendent. Le sommeil revient par bouts : encore court, encore fragile, mais il revient sans produit.",
     "The medical withdrawal is behind you. The tremor has stopped, blood pressure and pulse are coming down. Sleep returns in pieces: still short, still fragile, but it returns without the substance.",
     "انتهى السحب الطبي. توقفت الرعشة، وانخفض الضغط والنبض. يعود النوم على شكل مقاطع: قصيرًا وهشًّا، لكنه يعود دون المادة."),
    ("Les nuits se recollent", "The nights knit back together", "الليالي تلتئم"),
    ("Le sommeil se regroupe en un seul bloc au lieu de trois. C'est le premier signe fiable que le système nerveux se réinstalle — bien avant que l'humeur ne suive.",
     "Sleep gathers into one block instead of three. It is the first reliable sign that the nervous system is resettling — well before mood follows.",
     "يتجمّع النوم في كتلة واحدة بدل ثلاث. هذه أول علامة موثوقة على أن الجهاز العصبي يستعيد استقراره — قبل أن يتبعه المزاج بوقت طويل."),
    ("Ce que le produit cachait", "What the substance was hiding", "ما كانت المادة تخفيه"),
    ("Le produit ne masque plus rien. Ce qui reste apparaît en clair : une dépression, une anxiété, un trouble du sommeil ancien. C'est ici que le traitement psychiatrique prend le relais du sevrage.",
     "The substance masks nothing now. What is left shows plainly: a depression, an anxiety, a long-standing sleep disorder. This is where psychiatric treatment takes over from withdrawal.",
     "لم تعد المادة تحجب شيئًا. ما يبقى يظهر بوضوح: اكتئاب، أو قلق، أو اضطراب نوم قديم. هنا يتسلّم العلاج النفسي الراية من السحب."),
    ("Le matin redevient ordinaire", "The morning becomes ordinary again", "يعود الصباح عاديًا"),
    ("Se lever ne demande plus de courage. L'appétit revient, le poids se stabilise, la journée a de nouveau des heures fixes — repas, atelier, entretien, coucher.",
     "Getting up no longer takes courage. Appetite returns, weight stabilises, and the day has fixed hours again — meals, workshop, session, bedtime.",
     "لم يعد النهوض يحتاج شجاعة. تعود الشهية، ويستقر الوزن، ويستعيد اليوم مواعيده الثابتة — وجبات، وورشة، وجلسة، ونوم."),
    ("L'envie a un nom", "The urge has a name", "للرغبة اسم"),
    ("Les envies existent toujours — elles existeront longtemps. La différence, c'est qu'elles ont maintenant un nom, des déclencheurs identifiés, une réponse écrite à l'avance et quelqu'un à appeler.",
     "The urges are still there — they will be for a long time. The difference is that they now have a name, identified triggers, a response written in advance and someone to call.",
     "الرغبات ما تزال موجودة — وستبقى طويلًا. الفرق أنها صار لها اسم، ومحفّزات محدّدة، ورد مكتوب مسبقًا، وشخص يمكن الاتصال به."),
    ("Quatorze nuits d'affilée", "Fourteen nights in a row", "أربع عشرة ليلة متتالية"),
    ("Deux semaines de nuits complètes. C'est le repère que nous visons avant la sortie : pas l'absence d'envie, qui ne se commande pas, mais un sommeil qui tient tout seul.",
     "Two weeks of full nights. That is the marker we aim for before discharge: not the absence of urges, which cannot be commanded, but sleep that holds on its own.",
     "أسبوعان من ليالٍ كاملة. هذه هي العلامة التي نستهدفها قبل الخروج: لا غياب الرغبة، فهي لا تُطلَب، بل نوم يثبت من تلقاء نفسه."),
    ("Angoisse au réveil", "Dread on waking", "القلق عند الاستيقاظ"),
    ("3 h, en morceaux", "3 h, in pieces", "3 ساعات، مقطّعة"),
    ("5 h, d'un bloc", "5 h, in one block", "5 ساعات، متصلة"),
    ("7 h 30", "7 h 30", "7 ساعات ونصف"),
    ("maximale", "at its worst", "في أشدّها"),
    ("forte", "strong", "قوي"),
    ("présente", "present", "موجود"),
    ("variable", "variable", "متغيّر"),
    ("faible", "mild", "خفيف"),
    ("rare", "rare", "نادر"),
    ("À la Clinique Espoir, El Menzah 9 à Tunis, en hospitalisation complète, en hôpital de jour ou en consultation externe, selon ce que la situation demande.",
     "At Clinique Espoir, El Menzah 9 in Tunis — as a full inpatient stay, in day hospital, or as an outpatient, according to what the situation calls for.",
     "في عيادة الأمل، المنزه 9 بتونس — إقامة كاملة، أو مستشفى نهاري، أو استشارة خارجية، بحسب ما تقتضيه الحالة."),
    ("Choisir la langue", "Choose a language", "اختر اللغة"),
    # ── une journée ─────────────────────────────────────────────────────
    ("Une journée ici, heure par heure.", "A day here, hour by hour.", "يوم هنا، ساعةً بساعة."),
    ("Une journée, heure par heure", "A day, hour by hour", "يوم، ساعةً بساعة"),
    ("Une journée", "A day", "يوم"),
    ("Le rythme fait une partie du travail. Après des mois où plus rien n'avait d'horaire, le corps se remet en place parce que les repas, les ateliers et le coucher reviennent à la même heure chaque jour.",
     "Rhythm does part of the work. After months in which nothing had a fixed time, the body resettles because meals, workshops and bedtime come back at the same hour every day.",
     "الإيقاع يؤدي جزءًا من العمل. بعد أشهر لم يعد فيها لشيء موعد، يستعيد الجسد نظامه لأن الوجبات والورشات وموعد النوم تعود في الساعة نفسها كل يوم."),
    ("Ouvert 24 h/24, 7 j/7", "Open 24/7", "مفتوحة 24/24 و7/7"),
    (", toute l'année, jours fériés compris.", ", all year round, public holidays included.", "، طوال السنة، بما في ذلك أيام العطل."),
    ("Les urgences sont reçues", "Emergencies are seen", "تُستقبل الحالات الطارئة"),
    ("à toute heure", "at any hour", "في أي ساعة"),
    (", sans rendez-vous.", ", without an appointment.", "، دون موعد مسبق."),
    ("Consultations sur rendez-vous :", "Consultations by appointment:", "الاستشارات بموعد:"),
    ("lun–ven 8 h–18 h", "Mon–Fri 8 a.m.–6 p.m.", "الاثنين–الجمعة 8–18"),
    ("sam 8 h–13 h", "Sat 8 a.m.–1 p.m.", "السبت 8–13"),
    ("Exemple de journée en hospitalisation complète. Le programme est adapté à chaque patient et revu chaque semaine avec lui.",
     "An example day for a full inpatient stay. The programme is adapted to each patient and reviewed with them every week.",
     "مثال ليوم في الإقامة الكاملة. يُكيَّف البرنامج مع كل مريض ويُراجَع معه أسبوعيًا."),
    ("Réveil, prise des constantes", "Waking, vital signs taken", "الاستيقاظ وقياس العلامات الحيوية"),
    ("Petit-déjeuner en commun", "Breakfast together", "فطور جماعي"),
    ("Visite du psychiatre, entretien individuel", "Psychiatrist's round, one-to-one session", "زيارة الطبيب النفسي، جلسة فردية"),
    ("Atelier : art-thérapie, groupe de parole ou relaxation", "Workshop: art therapy, group session or relaxation", "ورشة: علاج بالفن أو مجموعة حديث أو استرخاء"),
    ("Déjeuner", "Lunch", "الغداء"),
    ("Temps libre : patio, lecture, marche accompagnée", "Free time: patio, reading, an accompanied walk", "وقت حر: الفناء، القراءة، مشي برفقة"),
    ("Psychothérapie individuelle ou entretien familial", "Individual psychotherapy or a family session", "علاج نفسي فردي أو جلسة عائلية"),
    ("Activité physique adaptée", "Adapted physical activity", "نشاط بدني مُكيَّف"),
    ("Dîner", "Dinner", "العشاء"),
    ("Veillée calme, passage infirmier, traitement du soir", "Quiet evening, nursing round, evening medication", "سهرة هادئة، مرور تمريضي، دواء المساء"),
    ("Nuit", "Night", "الليل"),
    ("Une équipe reste éveillée jusqu'au matin", "A team stays awake until morning", "فريق يبقى مستيقظًا حتى الصباح"),
    ("Ouvert 24 h/24, 7 j/7 — un médecin joignable à toute heure",
     "Open 24/7 — a doctor reachable at any hour",
     "مفتوحة 24/24 و7/7 — طبيب متاح في أي ساعة"),
    ("La clinique est ouverte 24 h/24 et 7 j/7 : chambres individuelles ou doubles, présence infirmière jour et nuit, transport médicalisé sur demande.",
     "The clinic is open 24 hours a day, 7 days a week: single or double rooms, nursing presence day and night, medical transport on request.",
     "العيادة مفتوحة 24 ساعة في اليوم، 7 أيام في الأسبوع: غرف فردية أو مزدوجة، ووجود تمريضي ليلًا ونهارًا، ونقل طبي عند الطلب."),
    # ── substances ajoutées ─────────────────────────────────────────────
    ("Toutes les substances sont prises en charge — alcool, drogues, médicaments détournés, tabac — ainsi que les addictions sans produit. Les durées ci-dessous sont indicatives : elles varient avec l'ancienneté de la consommation, les quantités, l'âge et l'état de santé général. Le protocole est décidé après examen.",
     "Every substance is treated — alcohol, drugs, diverted medicines, tobacco — as well as addictions with no substance at all. The durations below are indicative: they vary with how long use has gone on, the quantities, age and general health. The protocol is decided after examination.",
     "تُعالَج جميع المواد — الكحول، والمخدرات، والأدوية المحوَّلة عن استعمالها، والتبغ — إضافة إلى الإدمان دون مادة. المدد أدناه إرشادية: تتغيّر بحسب قِدَم الاستهلاك وكمياته وعمر الشخص وحالته الصحية العامة. يُقرَّر البروتوكول بعد الفحص."),
    ("Alcool, cannabis (zatla), cocaïne, opiacés, prégabaline, solvants, tabac",
     "Alcohol, cannabis (zatla), cocaine, opioids, pregabalin, solvents, tobacco",
     "الكحول، القنّب (الزطلة)، الكوكايين، المواد الأفيونية، البريغابالين، المذيبات، التبغ"),
    ("Opiacés — héroïne, tramadol, codéine", "Opioids — heroin, tramadol, codeine", "المواد الأفيونية — الهيروين، الترامادول، الكودايين"),
    ("Cocaïne, amphétamines, MDMA", "Cocaine, amphetamines, MDMA", "الكوكايين، الأمفيتامينات، إم دي إم إيه"),
    ("Cannabis — « zatla »", "Cannabis — “zatla”", "القنّب — «الزطلة»"),
    ("Cannabis, zatla", "Cannabis, zatla", "القنّب، الزطلة"),
    ("Prégabaline, Artane", "Pregabalin, Artane", "البريغابالين، الأرتان"),
    ("anxiété, douleur chronique, insomnie", "anxiety, chronic pain, insomnia", "قلق، ألم مزمن، أرق"),
    ("Sevrage — cannabis (zatla), cocaïne ou stimulants",
     "Withdrawal — cannabis (zatla), cocaine or stimulants", "سحب — قنّب (زطلة) أو كوكايين أو منشّطات"),
    ("Sevrage — prégabaline ou médicament détourné",
     "Withdrawal — pregabalin or a diverted medicine", "سحب — بريغابالين أو دواء محوَّل"),
    ("Sevrage — autre drogue", "Withdrawal — another drug", "سحب — مخدر آخر"),

    ("Prégabaline et médicaments détournés", "Pregabalin and diverted medicines", "البريغابالين والأدوية المحوَّلة"),
    ("Anxiété intense, insomnie, sueurs, douleurs, nausées, agitation. Un arrêt brutal de prégabaline à forte dose peut provoquer des convulsions. Le trihexyphénidyle donne confusion et hallucinations à l'arrêt comme à l'excès.",
     "Intense anxiety, insomnia, sweating, pain, nausea, agitation. Stopping high-dose pregabalin abruptly can cause seizures. Trihexyphenidyl produces confusion and hallucinations both in excess and on stopping.",
     "قلق شديد وأرق وتعرّق وآلام وغثيان وتهيّج. التوقف المفاجئ عن جرعات عالية من البريغابالين قد يسبّب نوبات تشنّجية. أما التريهكسيفينيديل فيسبّب تشوّشًا وهلوسة عند الإفراط وعند التوقف معًا."),
    ("Décroissance planifiée sur plusieurs semaines, jamais d'arrêt sec, traitement de l'anxiété et du sommeil, recherche systématique de la douleur ou du trouble qui a fait démarrer la prescription.",
     "A taper planned over several weeks, never a hard stop, treatment of anxiety and sleep, and a systematic search for the pain or the disorder that started the prescription.",
     "خفض مخطَّط له على مدى أسابيع، دون توقف مفاجئ أبدًا، ومعالجة القلق والنوم، وبحث منهجي عن الألم أو الاضطراب الذي بدأت به الوصفة."),
    ("4 à 12 semaines de décroissance selon la dose et l'ancienneté.",
     "A 4 to 12 week taper depending on dose and duration of use.",
     "خفض من 4 إلى 12 أسبوعًا بحسب الجرعة ومدة الاستعمال."),

    ("Kétamine et protoxyde d'azote", "Ketamine and nitrous oxide", "الكيتامين وأكسيد النيتروز"),
    ("Pas de syndrome de sevrage classique, mais craving fort, humeur basse et anxiété. Les dégâts sont ailleurs : atteinte de la vessie pour la kétamine, carence en vitamine B12 et atteinte des nerfs pour le protoxyde d'azote — fourmillements, faiblesse des jambes.",
     "No classic withdrawal syndrome, but strong craving, low mood and anxiety. The damage is elsewhere: bladder injury from ketamine, vitamin B12 deficiency and nerve damage from nitrous oxide — pins and needles, weakness in the legs.",
     "لا توجد متلازمة انسحاب تقليدية، لكن اشتهاء قوي وانخفاض في المزاج وقلق. الضرر في مكان آخر: إصابة المثانة مع الكيتامين، ونقص فيتامين ب12 وتلف الأعصاب مع أكسيد النيتروز — تنميل وضعف في الساقين."),
    ("Bilan neurologique et urologique, supplémentation en B12 quand elle est nécessaire, thérapie du craving, prise en charge de la dépression associée.",
     "Neurological and urological assessment, vitamin B12 supplementation where needed, craving therapy, treatment of the associated depression.",
     "تقييم عصبي وبولي، وتعويض فيتامين ب12 عند الحاجة، وعلاج الاشتهاء، ومعالجة الاكتئاب المصاحب."),
    ("Craving marqué 2 à 6 semaines ; les atteintes physiques se traitent à part.",
     "Marked craving for 2 to 6 weeks; the physical damage is treated separately.",
     "اشتهاء واضح من أسبوعين إلى ستة؛ وتُعالَج الأضرار الجسدية على حدة."),

    ("Hallucinogènes et nouvelles substances", "Hallucinogens and new substances", "المهلوسات والمواد الجديدة"),
    ("LSD, champignons, cathinones de synthèse : pas de dépendance physique, mais anxiété persistante, flash-backs et, chez les personnes vulnérables, déclenchement d'un épisode psychotique qui ne s'arrête pas avec le produit.",
     "LSD, mushrooms, synthetic cathinones: no physical dependence, but persistent anxiety, flashbacks and, in vulnerable people, a psychotic episode that does not stop when the substance does.",
     "إل إس دي، والفطر، والكاثينونات المُصنَّعة: لا اعتماد جسدي، لكن قلق مستمر، وارتجاعات، وعند الأشخاص القابلين للتأثر نوبة ذهانية لا تتوقف بتوقف المادة."),
    ("Mise à l'abri le temps de l'épisode aigu, traitement antipsychotique si les symptômes persistent, bilan psychiatrique complet.",
     "A safe place for the acute episode, antipsychotic treatment if symptoms persist, a full psychiatric assessment.",
     "مكان آمن خلال النوبة الحادة، وعلاج مضاد للذهان إذا استمرت الأعراض، وتقييم نفسي كامل."),
    ("Quelques jours pour l'épisode aigu ; un suivi plus long si un trouble s'installe.",
     "A few days for the acute episode; longer follow-up if a disorder sets in.",
     "أيام قليلة للنوبة الحادة؛ ومتابعة أطول إذا استقرّ اضطراب."),

    ("Solvants et produits inhalés", "Solvents and inhalants", "المذيبات والمواد المستنشَقة"),
    ("Colles, diluants, essence, gaz : maux de tête, tremblements, irritabilité, troubles de la concentration. Surtout chez les adolescents, et souvent caché longtemps par l'entourage.",
     "Glues, thinners, petrol, gas: headaches, tremor, irritability, trouble concentrating. Mostly in adolescents, and often hidden by the family for a long time.",
     "الغراء والمخفّفات والبنزين والغاز: صداع ورعشة وتهيّج وصعوبة تركيز. غالبًا لدى المراهقين، وكثيرًا ما يخفيه المحيطون طويلًا."),
    ("Bilan neurologique, hépatique et rénal — ces produits abîment vite — puis prise en charge familiale et scolaire autant que médicale.",
     "Neurological, liver and kidney assessment — these products do damage fast — then care that is as much about family and school as it is medical.",
     "تقييم عصبي وكبدي وكلوي — فهذه المواد تُتلف بسرعة — ثم رعاية عائلية ومدرسية بقدر ما هي طبية."),
    ("Manque physique bref ; la récupération cognitive demande des mois.",
     "Brief physical withdrawal; cognitive recovery takes months.",
     "انسحاب جسدي قصير؛ أما التعافي المعرفي فيستغرق أشهرًا."),
    ("Aller à une substance", "Jump to a substance", "انتقل إلى مادة"),
    ("Cannabis (zatla)", "Cannabis (zatla)", "القنّب (الزطلة)"),
    ("Kétamine", "Ketamine", "الكيتامين"),
    ("Hallucinogènes", "Hallucinogens", "المهلوسات"),
    ("Solvants", "Solvents", "المذيبات"),
    ("Jeu et écrans", "Gambling and screens", "القمار والشاشات"),
    ("Prégabaline", "Pregabalin", "البريغابالين"),
    ("Cocaïne", "Cocaine", "الكوكايين"),
    ("Pendant la phase aiguë, les constantes sont relevées plusieurs fois par jour : tension, pouls, température. C'est ce qui distingue un sevrage encadré d'un arrêt à la maison.",
     "During the acute phase, vital signs are taken several times a day: blood pressure, pulse, temperature. That is what separates a supervised withdrawal from stopping at home.",
     "خلال المرحلة الحادة، تُقاس العلامات الحيوية عدة مرات يوميًا: الضغط والنبض والحرارة. هذا ما يفرّق بين سحب تحت إشراف وتوقف في المنزل."),
    ("Un soignant mesure la tension artérielle d'un patient avec un brassard.",
     "A nurse taking a patient's blood pressure with a cuff.",
     "ممرّض يقيس ضغط دم مريض بجهاز الضغط."),
    ("Lumière du matin à travers les persiennes, sur le linge blanc d'un lit.",
     "Morning light through the blinds, across white bed linen.",
     "ضوء الصباح عبر الستائر، على بياضات السرير."),
    ("L'accueil", "Reception", "الاستقبال"),
    ("Les circulations", "The corridors", "الممرّات"),
    ("Chambre individuelle", "Single room", "غرفة فردية"),
    ("Chambre double", "Double room", "غرفة مزدوجة"),
    ("La consultation", "Consultation", "الاستشارة"),
    ("La présence infirmière, jour et nuit", "Nursing presence, day and night", "وجود تمريضي ليلًا ونهارًا"),
    ("Le groupe de parole", "The group session", "مجموعة الحديث"),
    ("Le salon commun", "The common room", "الصالون المشترك"),
    ("L'entretien", "The session", "الجلسة"),
    ("L'atelier", "The workshop", "الورشة"),
    ("La salle de relaxation", "The relaxation room", "غرفة الاسترخاء"),
    ("Hall d'accueil de la clinique, plantes et comptoir.",
     "The clinic's reception hall, plants and a desk.", "بهو استقبال العيادة، نباتات ومكتب."),
    ("Couloir clair de la clinique, sol carrelé et plante verte.",
     "A bright corridor, tiled floor and a plant.", "ممرّ مضيء، أرضية مبلّطة ونبتة."),
    ("Chambre individuelle claire, lit fait et table de chevet.",
     "A bright single room, bed made, bedside table.", "غرفة فردية مضيئة، سرير مرتّب وطاولة جانبية."),
    ("Un médecin reçoit en consultation un homme visiblement en difficulté.",
     "A doctor in consultation with a man visibly in distress.", "طبيب في استشارة مع رجل يبدو في ضائقة."),
    ("Chambre lumineuse avec une grande plante verte.",
     "A bright room with a large green plant.", "غرفة مضيئة مع نبتة خضراء كبيرة."),
    ("Une infirmière écoute une patiente, penchée vers elle.",
     "A nurse leaning in, listening to a patient.", "ممرّضة تنحني وتصغي إلى مريضة."),
    ("Chaises disposées en cercle pour un groupe de parole.",
     "Chairs arranged in a circle for a group session.", "كراسٍ مرتّبة في دائرة لمجموعة حديث."),
    ("Salon commun lumineux, canapés et plantes.",
     "A bright common room, sofas and plants.", "صالون مشترك مضيء، أرائك ونباتات."),
    ("Les mains d'un médecin, ouvertes, face à celles d'un patient.",
     "A doctor's open hands, facing a patient's.", "يدا طبيب مفتوحتان أمام يدي مريض."),
    ("Atelier d'art-thérapie, chevalets et grandes fenêtres.",
     "The art therapy workshop, easels and tall windows.", "ورشة العلاج بالفن، حوامل ونوافذ عالية."),
    ("Salle de relaxation sobre, lumière tamisée.",
     "A plain relaxation room, soft light.", "غرفة استرخاء بسيطة، إضاءة خافتة."),
    # ── SEO ─────────────────────────────────────────────────────────────
    ("Cure de sevrage alcool et drogue à Tunis — Clinique psychiatrique Espoir, El Menzah 9",
     "Alcohol and drug rehab in Tunis — Espoir Psychiatric Clinic, El Menzah 9",
     "علاج الإدمان من الكحول والمخدرات في تونس — عيادة الأمل النفسية، المنزه 9"),
    ("Cure de désintoxication et sevrage médicalisé à Tunis : alcool, cannabis (zatla), cocaïne, opiacés, prégabaline, solvants, tabac. Clinique psychiatrique ouverte 24 h/24 à El Menzah 9. Hospitalisation, hôpital de jour, consultations. Appelez le +216 00 000 000.",
     "Medically supervised detox and withdrawal in Tunis: alcohol, cannabis (zatla), cocaine, opioids, pregabalin, solvents, tobacco. Psychiatric clinic open 24/7 in El Menzah 9. Inpatient, day hospital, outpatient. Call +216 00 000 000.",
     "علاج إزالة السموم والسحب الطبي في تونس: الكحول، القنّب (الزطلة)، الكوكايين، المواد الأفيونية، البريغابالين، المذيبات، التبغ. عيادة نفسية مفتوحة 24/24 في المنزه 9. إقامة كاملة، مستشفى نهاري، استشارات. اتصل بـ +216 00 000 000."),
    ("Cure de sevrage et soins psychiatriques à Tunis",
     "Rehab and psychiatric care in Tunis", "علاج الإدمان والرعاية النفسية في تونس"),
    ("Cure de désintoxication et sevrage médicalisé, soins psychiatriques, hospitalisation et hôpital de jour à Tunis.",
     "Medically supervised detox and withdrawal, psychiatric care, inpatient and day hospital in Tunis.",
     "إزالة سموم وسحب طبي، ورعاية نفسية، وإقامة كاملة ومستشفى نهاري في تونس."),
    ("L'entrée de la Clinique Espoir, El Menzah 9, Tunis",
     "The entrance of Clinique Espoir, El Menzah 9, Tunis", "مدخل عيادة الأمل، المنزه 9، تونس"),
    ("Clinique psychiatrique Espoir", "Espoir Psychiatric Clinic", "عيادة الأمل النفسية"),
    # ── tête de page ────────────────────────────────────────────────────
    ("Sevrage et soins psychiatriques — Clinique Espoir, El Menzah 9",
     "Withdrawal and psychiatric care — Clinique Espoir, El Menzah 9",
     "علاج الانسحاب والرعاية النفسية — عيادة الأمل، المنزه 9"),
    ("Sevrage médicalisé (alcool, benzodiazépines, opiacés, cannabis, stimulants, tabac) et soins psychiatriques : comprendre le manque, le protocole, les troubles associés et le moment où il faut consulter. Service assuré à la Clinique Espoir, El Menzah 9, Tunis.",
     "Medically supervised withdrawal (alcohol, benzodiazepines, opioids, cannabis, stimulants, tobacco) and psychiatric care: what withdrawal really is, the protocol, the disorders underneath, and when to call. Provided at Clinique Espoir, El Menzah 9, Tunis.",
     "سحب طبي تحت إشراف (الكحول، البنزوديازيبينات، المواد الأفيونية، القنّب، المنشّطات، التبغ) ورعاية نفسية: فهم أعراض الانسحاب، والبروتوكول، والاضطرابات المصاحبة، ومتى يجب طلب المساعدة. تُقدَّم الخدمة في عيادة الأمل، المنزه 9، تونس."),
    ("Le manque a une physiologie : elle se surveille, elle se traite. Sevrage médicalisé et psychiatrie, à Tunis.",
     "Withdrawal has a physiology: it can be monitored, and it can be treated. Medical withdrawal and psychiatry, in Tunis.",
     "للانسحاب فسيولوجيا: تُراقَب وتُعالَج. سحب طبي وطب نفسي، في تونس."),

    # ── barre supérieure ────────────────────────────────────────────────
    ("Aller au contenu", "Skip to content", "انتقل إلى المحتوى"),
    ("Clinique psychiatrique Espoir, accueil", "Clinique Espoir psychiatric clinic, home", "عيادة الأمل النفسية، الصفحة الرئيسية"),
    ("Clinique psychiatrique · El Menzah 9", "Psychiatric clinic · El Menzah 9", "عيادة نفسية · المنزه 9"),
    ("Navigation principale", "Main navigation", "التنقّل الرئيسي"),
    ("Langue du site", "Site language", "لغة الموقع"),
    ("Urgence 24 h/24", "Emergency, 24/7", "طوارئ 24/24"),
    ("Ouvrir le menu", "Open the menu", "افتح القائمة"),
    ("Comprendre le manque", "Understanding withdrawal", "فهم الانسحاب"),
    ("Substance par substance", "Substance by substance", "مادة بمادة"),
    ("Le protocole de sevrage", "The withdrawal protocol", "بروتوكول السحب"),
    ("Addiction et trouble psychiatrique", "Addiction and psychiatric illness", "الإدمان والاضطراب النفسي"),
    ("Les troubles pris en charge.", "The disorders we treat.", "الاضطرابات التي نعالجها."),
    ("Les troubles pris en charge", "The disorders we treat", "الاضطرابات التي نعالجها"),
    ("Où se déroulent les soins", "Where the care happens", "أين تُقدَّم الرعاية"),
    ("Avant / après", "Before / after", "قبل / بعد"),
    ("Quand consulter", "When to call", "متى تتصل"),
    ("Les thérapies", "Therapies", "العلاجات"),
    ("Thérapies", "Therapies", "العلاجات"),
    ("Substances", "Substances", "المواد"),
    ("Protocole", "Protocol", "البروتوكول"),
    ("Troubles", "Disorders", "الاضطرابات"),
    ("Questions", "Questions", "أسئلة"),
    ("Contact", "Contact", "اتصل بنا"),

    # ── hero ────────────────────────────────────────────────────────────
    ("Le manque n'est pas", "Withdrawal is not", "الانسحاب ليس"),
    ("un manque de volonté.", "a lack of willpower.", "ضعفًا في الإرادة."),
    ("C'est un phénomène physiologique, mesurable, parfois dangereux — et qui se traite.",
     "It is a physiological event: measurable, sometimes dangerous — and treatable.",
     "إنه حدث فسيولوجي قابل للقياس، وخطير أحيانًا — وقابل للعلاج."),
    ("Sevrage médicalisé et soins psychiatriques",
     "Medically supervised withdrawal and psychiatric care",
     "سحب طبي تحت إشراف ورعاية نفسية"),
    (", assurés à la Clinique Espoir, El Menzah 9, Tunis.",
     ", provided at Clinique Espoir, El Menzah 9, Tunis.",
     "، تُقدَّم في عيادة الأمل، المنزه 9، تونس."),
    ("Appeler le +216 00 000 000", "Call +216 00 000 000", "اتصل بـ +216 00 000 000"),
    ("Comprendre le sevrage", "How withdrawal works", "كيف يجري السحب"),
    ("Alcool, benzodiazépines, opiacés, cannabis, stimulants, tabac",
     "Alcohol, benzodiazepines, opioids, cannabis, stimulants, tobacco",
     "الكحول، البنزوديازيبينات، المواد الأفيونية، القنّب، المنشّطات، التبغ"),
    ("Et le trouble psychiatrique qui se cache souvent dessous",
     "And the psychiatric disorder that is often hiding underneath",
     "والاضطراب النفسي الكامن تحتها غالبًا"),
    ("Un médecin joignable à toute heure", "A doctor reachable at any hour", "طبيب متاح في أي ساعة"),
    ("Façade blanche de la Clinique de l'Espoir, enseigne bleue au-dessus d'une porte vitrée.",
     "The white facade of Clinique de l'Espoir, blue sign above a glass door.",
     "واجهة بيضاء لعيادة الأمل، ولوحة زرقاء فوق باب زجاجي."),
    ("Le service est assuré à la Clinique Espoir, El Menzah 9.",
     "The service is provided at Clinique Espoir, El Menzah 9.",
     "تُقدَّم الخدمة في عيادة الأمل، المنزه 9."),

    # ── bandeau urgence ─────────────────────────────────────────────────
    ("Numéro d'urgence", "Emergency number", "رقم الطوارئ"),
    ("Convulsion, confusion, hallucinations pendant un arrêt ? Appelez le",
     "Seizure, confusion or hallucinations while stopping? Call",
     "تشنّج أو تشوّش أو هلوسة أثناء التوقف؟ اتصل بـ"),
    ("— 24 h/24.", "— 24/7.", "— على مدار الساعة."),
    ("Danger vital immédiat : composez également le",
     "Immediate danger to life: also dial",
     "خطر مباشر على الحياة: اتصل أيضًا بـ"),
    ("(SAMU).", "(ambulance service).", "(الإسعاف)."),

    # ── comprendre ──────────────────────────────────────────────────────
    ("Ce que fait le corps quand le produit s'arrête.",
     "What the body does when the substance stops.",
     "ماذا يفعل الجسم حين تتوقف المادة."),
    ("Une consommation prolongée déplace l'équilibre du système nerveux. Le cerveau compense en permanence l'effet du produit ; quand le produit disparaît, cette compensation reste seule en piste. C'est le syndrome de manque — et selon la substance, il va de l'inconfort majeur au risque vital.",
     "Prolonged use shifts the balance of the nervous system. The brain is permanently compensating for the substance; when the substance goes, that compensation is left running alone. That is withdrawal — and depending on the substance it ranges from severe discomfort to a threat to life.",
     "الاستهلاك المطوّل يزيح توازن الجهاز العصبي. يعوّض الدماغ باستمرار أثر المادة؛ وحين تختفي المادة يبقى هذا التعويض وحده في الميدان. هذه هي أعراض الانسحاب — وتتراوح بحسب المادة بين انزعاج شديد وخطر على الحياة."),
    ("Le manque physique", "Physical withdrawal", "الانسحاب الجسدي"),
    ("Tremblements, sueurs, tachycardie, tension qui monte, nausées, insomnie, anxiété massive. Il commence quelques heures après la dernière prise et culmine en général entre le deuxième et le troisième jour.",
     "Tremor, sweating, racing heart, rising blood pressure, nausea, insomnia, overwhelming anxiety. It starts a few hours after the last dose and usually peaks between the second and third day.",
     "رعشة وتعرّق وتسارع في النبض وارتفاع في الضغط وغثيان وأرق وقلق شديد. يبدأ بعد ساعات من آخر جرعة ويبلغ ذروته عادة بين اليوم الثاني والثالث."),
    ("Les formes graves", "The severe forms", "الأشكال الخطيرة"),
    ("Pour l'alcool et les benzodiazépines, un arrêt brutal peut provoquer des crises convulsives et un delirium tremens — confusion, hallucinations, fièvre, déshydratation. C'est une urgence médicale, pas une mauvaise nuit à passer.",
     "For alcohol and benzodiazepines, stopping abruptly can cause seizures and delirium tremens — confusion, hallucinations, fever, dehydration. That is a medical emergency, not a rough night to get through.",
     "مع الكحول والبنزوديازيبينات، قد يسبّب التوقف المفاجئ نوبات تشنّجية وهذيانًا ارتعاشيًا — تشوّشًا وهلوسة وحمّى وجفافًا. هذه حالة طوارئ طبية، لا ليلة صعبة تُحتمل."),
    ("Le craving", "Craving", "الاشتهاء القهري"),
    ("Une fois le corps désintoxiqué, l'envie irrépressible reste. Elle se déclenche par des lieux, des personnes, des horaires, une émotion. C'est elle qui fait rechuter, et c'est elle que le travail thérapeutique vise.",
     "Once the body is detoxified, the compulsion remains. It is triggered by places, people, times of day, an emotion. It is what causes relapse, and it is what the therapeutic work is aimed at.",
     "بعد أن يتخلّص الجسم من السموم، تبقى الرغبة القهرية. تُستثار بأماكن وأشخاص ومواعيد وانفعالات. هي سبب الانتكاس، وهي هدف العمل العلاجي."),
    ("Pourquoi ne pas arrêter seul", "Why not to stop alone", "لماذا لا تتوقف وحدك"),
    ("Un sevrage d'alcool ou de benzodiazépines conduit sans encadrement médical expose à des convulsions, à un delirium tremens et à des complications cardiaques ou métaboliques. Un sevrage encadré traite ces risques avant qu'ils n'apparaissent : surveillance des constantes, traitement adapté, hydratation, vitamine B1. Il rend aussi l'épreuve nettement moins pénible — ce qui change tout sur la suite.",
     "Alcohol or benzodiazepine withdrawal carried out without medical supervision exposes you to seizures, delirium tremens and cardiac or metabolic complications. Supervised withdrawal treats those risks before they appear: monitoring of vital signs, an adapted protocol, hydration, vitamin B1. It also makes the ordeal markedly less painful — which changes everything about what follows.",
     "الانسحاب من الكحول أو البنزوديازيبينات دون إشراف طبي يعرّضك لنوبات تشنّجية وهذيان ارتعاشي ومضاعفات قلبية أو استقلابية. أمّا السحب المُشرَف عليه فيعالج هذه المخاطر قبل ظهورها: مراقبة العلامات الحيوية، وبروتوكول ملائم، وإماهة، وفيتامين ب1. كما يجعل التجربة أقل إيلامًا بكثير — وهذا يغيّر كل ما يأتي بعدها."),

    # ── substances ──────────────────────────────────────────────────────
    ("Chaque produit a son propre sevrage.", "Every substance has its own withdrawal.", "لكل مادة انسحابها الخاص."),
    ("Les durées ci-dessous sont indicatives : elles varient avec l'ancienneté de la consommation, les quantités, l'âge et l'état de santé général. Le protocole est décidé après examen.",
     "The durations below are indicative: they vary with how long use has gone on, the quantities, age and general health. The protocol is decided after examination.",
     "المدد أدناه إرشادية: تتغيّر بحسب قِدَم الاستهلاك وكمياته وعمر الشخص وحالته الصحية العامة. يُقرَّر البروتوكول بعد الفحص."),
    ("Signes du manque", "Withdrawal signs", "علامات الانسحاب"),
    ("Prise en charge :", "Treatment:", "العلاج:"),
    ("Prise en charge", "Treatment", "العلاج"),
    ("Durée", "Duration", "المدة"),
    ("Tremblements, sueurs, anxiété, nausées, insomnie dès 6 à 12 h. Convulsions possibles dans les 48 h, delirium tremens entre 48 et 96 h.",
     "Tremor, sweating, anxiety, nausea, insomnia from 6 to 12 hours. Seizures possible within 48 hours, delirium tremens between 48 and 96 hours.",
     "رعشة وتعرّق وقلق وغثيان وأرق بدءًا من 6 إلى 12 ساعة. نوبات تشنّجية محتملة خلال 48 ساعة، وهذيان ارتعاشي بين 48 و96 ساعة."),
    ("Sevrage hospitalier, benzodiazépines à doses dégressives sous surveillance, hydratation, vitamine B1 pour prévenir les complications neurologiques.",
     "Inpatient withdrawal, benzodiazepines on a tapering dose under monitoring, hydration, vitamin B1 to prevent neurological complications.",
     "سحب داخل المستشفى، وبنزوديازيبينات بجرعات متناقصة تحت المراقبة، وإماهة، وفيتامين ب1 للوقاية من المضاعفات العصبية."),
    ("Phase aiguë 5 à 7 jours ; fatigue et troubles du sommeil pendant plusieurs semaines.",
     "Acute phase 5 to 7 days; fatigue and disturbed sleep for several weeks.",
     "المرحلة الحادة من 5 إلى 7 أيام؛ وإرهاق واضطراب في النوم لأسابيع."),
    ("Benzodiazépines et somnifères", "Benzodiazepines and sleeping pills", "البنزوديازيبينات والمنوّمات"),
    ("Anxiété de rebond, insomnie sévère, douleurs musculaires, troubles de la perception. Risque convulsif réel en cas d'arrêt brutal.",
     "Rebound anxiety, severe insomnia, muscle pain, perceptual disturbance. A real seizure risk if stopped abruptly.",
     "قلق ارتدادي وأرق شديد وآلام عضلية واضطراب في الإدراك. خطر تشنّج حقيقي عند التوقف المفاجئ."),
    ("Jamais d'arrêt sec : relais vers une molécule à demi-vie longue puis décroissance lente et planifiée, palier par palier, avec accompagnement de l'anxiété.",
     "Never a hard stop: switch to a long half-life molecule, then a slow, planned taper, step by step, with the anxiety treated alongside.",
     "لا توقف مفاجئ أبدًا: الانتقال إلى جزيء طويل نصف العمر، ثم خفض بطيء مخطَّط له، درجةً درجة، مع معالجة القلق في الوقت نفسه."),
    ("Plusieurs semaines à plusieurs mois. La lenteur n'est pas un échec, c'est le protocole.",
     "Several weeks to several months. Slowness is not failure here; it is the protocol.",
     "من أسابيع إلى أشهر. البطء ليس فشلًا هنا، بل هو البروتوكول."),
    ("Opiacés", "Opioids", "المواد الأفيونية"),
    ("Douleurs diffuses, crampes, diarrhée, larmoiement, bâillements, frissons, insomnie, angoisse. Rarement mortel, mais très difficile à traverser seul.",
     "Diffuse pain, cramps, diarrhoea, watering eyes, yawning, shivering, insomnia, dread. Rarely fatal, but very hard to get through alone.",
     "آلام منتشرة وتقلّصات وإسهال ودموع وتثاؤب وقشعريرة وأرق وضيق. نادرًا ما يكون مميتًا، لكنه صعب جدًا بمفردك."),
    ("Traitement symptomatique, ou traitement de substitution (méthadone, buprénorphine) lorsqu'il est indiqué, avec suivi rapproché.",
     "Symptomatic treatment, or substitution treatment (methadone, buprenorphine) where indicated, with close follow-up.",
     "علاج للأعراض، أو علاج إحلالي (الميثادون، البوبرينورفين) عند الحاجة، مع متابعة لصيقة."),
    ("Phase aiguë 5 à 10 jours ; troubles du sommeil et de l'humeur plus longtemps.",
     "Acute phase 5 to 10 days; sleep and mood disturbance for longer.",
     "المرحلة الحادة من 5 إلى 10 أيام؛ واضطراب النوم والمزاج لمدة أطول."),
    ("Cannabis", "Cannabis", "القنّب"),
    ("Irritabilité, colère, anxiété, insomnie et rêves intenses, perte d'appétit, humeur basse. Chez certains, révélation ou aggravation de symptômes psychotiques.",
     "Irritability, anger, anxiety, insomnia and vivid dreams, loss of appetite, low mood. In some people it reveals or worsens psychotic symptoms.",
     "تهيّج وغضب وقلق وأرق وأحلام مكثّفة وفقدان شهية وانخفاض في المزاج. وعند بعض الأشخاص يكشف أعراضًا ذهانية أو يفاقمها."),
    ("Accompagnement du sommeil et de l'anxiété, entretien motivationnel, bilan psychiatrique si des symptômes persistent au-delà du sevrage.",
     "Support for sleep and anxiety, motivational interviewing, a psychiatric assessment if symptoms outlast the withdrawal.",
     "دعم النوم والقلق، ومقابلة تحفيزية، وتقييم نفسي إذا استمرت الأعراض بعد انتهاء الانسحاب."),
    ("1 à 3 semaines pour le plus fort ; le craving se travaille ensuite.",
     "1 to 3 weeks for the worst of it; the craving is worked on afterwards.",
     "من أسبوع إلى ثلاثة أسابيع لأشدّه؛ ثم يُعالَج الاشتهاء بعد ذلك."),
    ("Cocaïne et stimulants", "Cocaine and stimulants", "الكوكايين والمنشّطات"),
    ("Effondrement de l'humeur, hypersomnie, ralentissement, faim intense, craving violent. Le risque principal est dépressif et suicidaire, pas cardiovasculaire.",
     "Mood collapse, hypersomnia, slowing, intense hunger, violent craving. The main risk is depressive and suicidal, not cardiovascular.",
     "انهيار في المزاج وفرط نوم وبطء وجوع شديد واشتهاء عنيف. الخطر الأساسي اكتئابي وانتحاري، لا قلبي وعائي."),
    ("Surveillance de l'humeur et du risque suicidaire, remise en route du sommeil, traitement d'un épisode dépressif s'il s'installe, thérapie du craving.",
     "Monitoring of mood and suicide risk, restarting sleep, treatment of a depressive episode if one sets in, therapy for craving.",
     "مراقبة المزاج وخطر الانتحار، وإعادة تنظيم النوم، وعلاج نوبة اكتئابية إن استقرّت، وعلاج الاشتهاء."),
    ("Descente sur 3 à 10 jours ; vulnérabilité dépressive pendant plusieurs semaines.",
     "The crash lasts 3 to 10 days; depressive vulnerability for several weeks.",
     "الهبوط من 3 إلى 10 أيام؛ وقابلية للاكتئاب لعدة أسابيع."),
    ("Tabac", "Tobacco", "التبغ"),
    ("Irritabilité, difficulté de concentration, agitation, appétit augmenté, envie ponctuelle très forte mais brève.",
     "Irritability, difficulty concentrating, restlessness, increased appetite, very strong but short-lived urges.",
     "تهيّج وصعوبة تركيز وتململ وزيادة شهية ونوبات رغبة قوية جدًا لكنها قصيرة."),
    ("Substituts nicotiniques dosés correctement, gestion des situations déclenchantes, prise en compte de l'interaction avec les traitements psychiatriques.",
     "Correctly dosed nicotine replacement, management of trigger situations, attention to interactions with psychiatric medication.",
     "بدائل نيكوتين بجرعات صحيحة، وإدارة المواقف المحفّزة، ومراعاة التداخل مع الأدوية النفسية."),
    ("Manque physique 2 à 4 semaines ; le geste et l'habitude durent plus longtemps.",
     "Physical withdrawal 2 to 4 weeks; the gesture and the habit last longer.",
     "الانسحاب الجسدي من أسبوعين إلى أربعة؛ أما العادة والحركة فتدومان أطول."),
    ("Jeu, écrans, achats", "Gambling, screens, spending", "القمار والشاشات والشراء"),
    ("Pas de sevrage physique, mais irritabilité, agitation, envie envahissante, et souvent une situation financière ou familiale déjà abîmée.",
     "No physical withdrawal, but irritability, restlessness, invasive urges — and often finances or a family already damaged.",
     "لا انسحاب جسدي، لكن تهيّج وتململ ورغبة مُلحّة، وغالبًا وضع مالي أو عائلي متضرّر بالفعل."),
    ("Thérapie cognitivo-comportementale, mesures concrètes d'exposition et de contrôle, prise en charge de la honte, travail avec l'entourage.",
     "Cognitive behavioural therapy, concrete exposure and control measures, work on shame, work with those around the person.",
     "علاج معرفي سلوكي، وإجراءات ملموسة للتعرّض والضبط، ومعالجة الشعور بالعار، وعمل مع المحيطين."),
    ("Programme de plusieurs mois, en ambulatoire ou en hôpital de jour.",
     "A programme of several months, as an outpatient or in day hospital.",
     "برنامج يمتد أشهرًا، في العيادات الخارجية أو في مستشفى النهار."),
    ("Plusieurs produits à la fois ?", "Several substances at once?", "عدة مواد في آنٍ واحد؟"),
    ("C'est le cas le plus fréquent, et celui qu'il ne faut surtout pas gérer seul : les sevrages s'additionnent et se masquent. Décrivez la situation au téléphone, l'ordre des priorités se décide médicalement.",
     "This is the most common case, and the one you must not handle alone: withdrawals add up and mask one another. Describe the situation on the phone; the order of priorities is a medical decision.",
     "هذه أكثر الحالات شيوعًا، وهي التي لا ينبغي أبدًا التعامل معها بمفردك: أعراض الانسحاب تتراكم ويحجب بعضها بعضًا. اشرح الحالة عبر الهاتف، وترتيب الأولويات قرار طبي."),

    # ── protocole ───────────────────────────────────────────────────────
    ("Le protocole, du premier jour jusqu'au dernier.",
     "The protocol, from the first day to the last.",
     "البروتوكول، من اليوم الأول إلى الأخير."),
    ("Un sevrage réussi ne s'arrête pas quand les tremblements cessent. La désintoxication est la partie courte ; ce qui décide de la suite, c'est ce qu'on construit pendant et après.",
     "A successful withdrawal does not end when the shaking stops. Detoxification is the short part; what decides the rest is what gets built during and after it.",
     "السحب الناجح لا ينتهي حين تتوقف الرعشة. إزالة السموم هي الجزء القصير؛ وما يحدّد ما بعدها هو ما يُبنى خلالها وبعدها."),
    ("Parler à un médecin", "Speak to a doctor", "تحدّث إلى طبيب"),
    ("Bilan d'entrée", "Admission assessment", "تقييم الدخول"),
    ("Examen clinique, bilan biologique, hépatique et cardiaque, évaluation de la sévérité de la dépendance et recherche des troubles associés — anxiété, dépression, sommeil, risque suicidaire. Rien ne commence avant d'avoir mesuré le terrain.",
     "Clinical examination, blood work, liver and cardiac assessment, grading of dependence severity, and a search for associated disorders — anxiety, depression, sleep, suicide risk. Nothing begins before the ground has been measured.",
     "فحص سريري، وتحاليل دم، وتقييم للكبد والقلب، وتحديد شدّة الاعتماد، والبحث عن الاضطرابات المصاحبة — القلق والاكتئاب والنوم وخطر الانتحار. لا شيء يبدأ قبل قياس الأرضية."),
    ("Jour 1", "Day 1", "اليوم 1"),
    ("Sevrage médicalisé", "Medically supervised withdrawal", "سحب تحت إشراف طبي"),
    ("Le syndrome de manque est traité, pas subi : protocole propre à la substance, doses dégressives, surveillance des constantes plusieurs fois par jour, hydratation, vitamines, prévention des convulsions et du delirium.",
     "Withdrawal is treated, not endured: a protocol specific to the substance, tapering doses, vital signs checked several times a day, hydration, vitamins, prevention of seizures and delirium.",
     "تُعالَج أعراض الانسحاب ولا تُحتمَل فقط: بروتوكول خاص بكل مادة، وجرعات متناقصة، ومراقبة للعلامات الحيوية عدة مرات يوميًا، وإماهة، وفيتامينات، ووقاية من التشنّجات والهذيان."),
    ("Jours 1 à 7 environ", "Days 1 to 7, roughly", "من اليوم 1 إلى 7 تقريبًا"),
    ("Stabilisation", "Stabilisation", "الاستقرار"),
    ("Le sommeil se remet en place, l'appétit revient, l'humeur se relève ou révèle ce qu'elle cachait. C'est là que se traite le trouble psychiatrique masqué par le produit, et que la journée retrouve des heures fixes.",
     "Sleep re-establishes itself, appetite returns, mood lifts — or reveals what it had been hiding. This is where the psychiatric disorder the substance was masking gets treated, and where the day gets its fixed hours back.",
     "يعود النوم إلى نظامه، وتعود الشهية، ويرتفع المزاج أو يكشف ما كان يخفيه. هنا يُعالَج الاضطراب النفسي الذي كانت المادة تحجبه، ويستعيد اليوم مواعيده الثابتة."),
    ("Semaines 1 à 3", "Weeks 1 to 3", "الأسابيع 1 إلى 3"),
    ("Travail sur le craving", "Working on craving", "العمل على الاشتهاء"),
    ("Entretien motivationnel, thérapie cognitivo-comportementale, groupe de parole entre pairs, repérage des situations à risque, plan écrit pour les moments de bascule, et un travail avec l'entourage quand il est possible.",
     "Motivational interviewing, cognitive behavioural therapy, peer group work, identifying high-risk situations, a written plan for the tipping moments, and work with the family where that is possible.",
     "مقابلة تحفيزية، وعلاج معرفي سلوكي، ومجموعة دعم بين الأقران، وتحديد المواقف عالية الخطورة، وخطة مكتوبة للحظات الحرجة، وعمل مع المحيطين متى أمكن."),
    ("Tout au long du séjour", "Throughout the stay", "طوال فترة الإقامة"),
    ("Après la sortie", "After discharge", "بعد الخروج"),
    ("Consultations rapprochées, poursuite du traitement, entretien familial, orientation vers un groupe d'entraide et vers le médecin traitant. Le premier mois dehors est le plus fragile : il est suivi de près.",
     "Close follow-up appointments, continued treatment, a family session, referral to a peer support group and to the family doctor. The first month outside is the most fragile: it is followed closely.",
     "مواعيد متابعة متقاربة، ومواصلة العلاج، وجلسة عائلية، وتوجيه إلى مجموعة دعم وإلى طبيب الأسرة. الشهر الأول خارج العيادة هو الأكثر هشاشة: تجري متابعته عن قرب."),
    ("3 à 12 mois", "3 to 12 months", "من 3 إلى 12 شهرًا"),

    # ── avant / après ───────────────────────────────────────────────────
    ("Ce que six semaines changent.", "What six weeks change.", "ما الذي تغيّره ستة أسابيع."),
    ("Jour 0", "Day 0", "اليوم 0"),
    ("Illustration, et non la photographie d'un patient. Elle représente un profil d'évolution courant après un sevrage encadré ; l'évolution réelle varie d'une personne à l'autre.",
     "An illustration, not a photograph of a patient. It shows a common course after supervised withdrawal; real outcomes vary from person to person.",
     "رسم توضيحي، لا صورة لمريض. يمثّل مسارًا شائعًا بعد سحب مُشرَف عليه؛ والنتائج الفعلية تختلف من شخص لآخر."),
    ("Sommeil", "Sleep", "النوم"),
    ("Anxiété", "Anxiety", "القلق"),
    ("Craving", "Craving", "الاشتهاء"),

    # ── double diagnostic ───────────────────────────────────────────────
    ("Sous l'addiction, presque toujours autre chose.",
     "Underneath the addiction, almost always something else.",
     "تحت الإدمان، شيء آخر دائمًا تقريبًا."),
    ("On boit rarement sans raison. L'alcool endort une anxiété, la cocaïne relance une dépression, le cannabis éteint des idées qui tournent, les somnifères réparent des nuits que le trouble bipolaire a détruites. Traiter la consommation sans traiter ce qu'elle compense, c'est organiser la rechute.",
     "People rarely drink for no reason. Alcohol puts an anxiety to sleep, cocaine restarts a depression, cannabis switches off thoughts that keep circling, sleeping pills repair nights that bipolar disorder destroyed. Treating the use without treating what it compensates for is simply organising the relapse.",
     "نادرًا ما يشرب المرء بلا سبب. الكحول ينوّم قلقًا، والكوكايين يُعيد إشعال اكتئاب، والقنّب يُطفئ أفكارًا لا تتوقف، والمنوّمات ترمّم ليالي دمّرها الاضطراب ثنائي القطب. معالجة الاستهلاك دون معالجة ما يعوّضه هي تنظيم للانتكاس."),
    ("C'est pourquoi le sevrage est ici un acte psychiatrique : le même médecin conduit la désintoxication et prend en charge le trouble qui apparaît derrière, une fois le produit retiré.",
     "That is why withdrawal here is a psychiatric act: the same doctor runs the detoxification and treats the disorder that appears behind it, once the substance is gone.",
     "لذلك فإن السحب هنا فعل نفسي: الطبيب نفسه يدير إزالة السموم ويعالج الاضطراب الذي يظهر خلفها بعد زوال المادة."),
    ("anxiété, dépression, stress post-traumatique",
     "anxiety, depression, post-traumatic stress", "قلق، اكتئاب، كرب ما بعد الصدمة"),
    ("Benzodiazépines", "Benzodiazepines", "البنزوديازيبينات"),
    ("insomnie chronique, trouble anxieux", "chronic insomnia, anxiety disorder", "أرق مزمن، اضطراب قلق"),
    ("troubles psychotiques, phobie sociale", "psychotic disorders, social phobia", "اضطرابات ذهانية، رهاب اجتماعي"),
    ("Cocaïne, stimulants", "Cocaine, stimulants", "كوكايين، منشّطات"),
    ("trouble bipolaire, dépression", "bipolar disorder, depression", "اضطراب ثنائي القطب، اكتئاب"),
    ("douleur chronique, dépression", "chronic pain, depression", "ألم مزمن، اكتئاب"),
    ("Jeu, écrans", "Gambling, screens", "قمار، شاشات"),
    ("impulsivité, trouble de la personnalité", "impulsivity, personality disorder", "اندفاعية، اضطراب شخصية"),
    ("Alcool", "Alcohol", "الكحول"),

    # ── troubles ────────────────────────────────────────────────────────
    ("Avec ou sans addiction associée. Ces descriptions servent à reconnaître, pas à diagnostiquer : seul un entretien médical peut poser un diagnostic.",
     "With or without an associated addiction. These descriptions are here to help you recognise, not to diagnose: only a medical consultation can make a diagnosis.",
     "مع إدمان مصاحب أو دونه. هذه الأوصاف للتعرّف لا للتشخيص: التشخيص لا يصدر إلا عن استشارة طبية."),
    ("Dépression", "Depression", "الاكتئاب"),
    ("Une tristesse ou une perte d'intérêt qui dure plus de deux semaines, presque toute la journée, presque tous les jours. S'y ajoutent souvent le sommeil qui se casse — réveils à 4 h du matin —, l'appétit qui change, la fatigue au réveil, la lenteur, la culpabilité, et parfois l'idée que tout le monde s'en porterait mieux.",
     "Sadness or loss of interest lasting more than two weeks, most of the day, nearly every day. Often joined by broken sleep — waking at 4 a.m. — a changed appetite, tiredness on waking, slowness, guilt, and sometimes the thought that everyone would be better off.",
     "حزن أو فقدان اهتمام يستمر أكثر من أسبوعين، معظم اليوم، ومعظم الأيام. يرافقه غالبًا نوم متقطّع — استيقاظ في الرابعة فجرًا — وتغيّر في الشهية، وإرهاق عند الاستيقاظ، وبطء، وشعور بالذنب، وأحيانًا فكرة أن الجميع سيكون أفضل حالًا."),
    ("psychothérapie, antidépresseur quand il est indiqué, remise en route du rythme et de l'activité. L'hospitalisation se justifie quand il y a un risque suicidaire, un refus de s'alimenter, ou quand rien ne bouge en ambulatoire.",
     "psychotherapy, an antidepressant where indicated, restarting rhythm and activity. Admission is warranted when there is suicide risk, refusal to eat, or when nothing moves in outpatient care.",
     "علاج نفسي، ومضاد اكتئاب عند الحاجة، وإعادة تشغيل الإيقاع والنشاط. يُبرَّر الإدخال عند وجود خطر انتحار أو رفض للطعام أو حين لا يتحرك شيء في العيادة الخارجية."),
    ("Trouble bipolaire", "Bipolar disorder", "الاضطراب ثنائي القطب"),
    ("Une alternance entre des épisodes dépressifs et des phases d'exaltation : besoin de sommeil effondré sans fatigue, débit de parole accéléré, dépenses, projets démesurés, irritabilité, désinhibition. Entre les épisodes, l'état peut être parfaitement normal, ce qui retarde souvent le diagnostic de plusieurs années.",
     "An alternation between depressive episodes and phases of elation: a collapsed need for sleep without tiredness, accelerated speech, spending, outsized plans, irritability, disinhibition. Between episodes a person can be perfectly well, which often delays diagnosis by years.",
     "تناوب بين نوبات اكتئابية ومراحل ابتهاج: انهيار الحاجة إلى النوم دون تعب، وتسارع الكلام، وإنفاق، ومشاريع مفرطة، وتهيّج، وانفلات في الضوابط. بين النوبات قد تكون الحال طبيعية تمامًا، ما يؤخّر التشخيص سنوات."),
    ("thymorégulateurs, protection du sommeil, psychoéducation du patient et de la famille pour reconnaître les signes précoces d'un nouvel épisode. Les consommations d'alcool et de stimulants aggravent nettement l'évolution.",
     "mood stabilisers, protection of sleep, psychoeducation of patient and family so early signs of a new episode get recognised. Alcohol and stimulant use markedly worsens the course.",
     "مثبّتات مزاج، وحماية للنوم، وتثقيف نفسي للمريض وعائلته للتعرّف على العلامات المبكرة لنوبة جديدة. الكحول والمنشّطات تُفاقم المسار بوضوح."),
    ("Troubles anxieux", "Anxiety disorders", "اضطرابات القلق"),
    ("Anxiété généralisée qui tourne en continu, attaques de panique avec sensation de mort imminente, phobies, trouble obsessionnel compulsif, état de stress post-traumatique. L'anxiété fait consommer : c'est le premier motif d'automédication par l'alcool et les somnifères.",
     "Generalised anxiety running continuously, panic attacks with a sense of imminent death, phobias, obsessive-compulsive disorder, post-traumatic stress. Anxiety drives use: it is the leading reason people self-medicate with alcohol and sleeping pills.",
     "قلق معمّم لا يتوقف، ونوبات هلع مع إحساس بالموت الوشيك، ورهاب، ووسواس قهري، وكرب ما بعد الصدمة. القلق يدفع إلى الاستهلاك: وهو السبب الأول للتداوي الذاتي بالكحول والمنوّمات."),
    ("thérapie cognitivo-comportementale et exposition graduée, relaxation, traitement de fond si nécessaire — en évitant précisément les benzodiazépines au long cours.",
     "cognitive behavioural therapy and graded exposure, relaxation, maintenance medication if needed — while specifically avoiding long-term benzodiazepines.",
     "علاج معرفي سلوكي وتعرّض متدرّج، واسترخاء، وعلاج صيانة عند اللزوم — مع تجنّب البنزوديازيبينات طويلة الأمد تحديدًا."),
    ("Troubles psychotiques", "Psychotic disorders", "الاضطرابات الذهانية"),
    ("Hallucinations, convictions délirantes de persécution, discours désorganisé, retrait, méfiance envers les proches. Souvent le patient ne se vit pas comme malade, ce qui rend la démarche impossible sans la famille.",
     "Hallucinations, delusional convictions of persecution, disorganised speech, withdrawal, suspicion of those closest. Often the person does not experience themselves as ill, which makes the step impossible without the family.",
     "هلوسات، وقناعات ضلالية بالاضطهاد، وكلام مفكّك، وانسحاب، وارتياب من المقرّبين. غالبًا لا يرى المريض نفسه مريضًا، ما يجعل الخطوة مستحيلة دون العائلة."),
    ("traitement antipsychotique, mise à l'abri le temps de la phase aiguë, réhabilitation ensuite. La précocité de la prise en charge pèse lourd sur l'évolution à long terme.",
     "antipsychotic treatment, a safe place for the acute phase, rehabilitation afterwards. How early care starts weighs heavily on the long-term course.",
     "علاج مضاد للذهان، ومكان آمن خلال المرحلة الحادة، ثم إعادة تأهيل. باكورة العلاج تؤثر كثيرًا في المسار بعيد المدى."),
    ("Troubles du sommeil", "Sleep disorders", "اضطرابات النوم"),
    ("Insomnie d'endormissement ou de milieu de nuit, hypersomnie, inversion du rythme, cauchemars répétés. Rarement isolé : le sommeil est le premier symptôme à se dérégler dans presque toutes les pathologies psychiatriques, et le dernier à se réparer après un sevrage.",
     "Insomnia at onset or in the middle of the night, hypersomnia, an inverted rhythm, repeated nightmares. Rarely isolated: sleep is the first thing to go wrong in almost every psychiatric condition, and the last to repair after a withdrawal.",
     "أرق في بداية النوم أو في منتصف الليل، وفرط نوم، وانقلاب في الإيقاع، وكوابيس متكرّرة. نادرًا ما يكون منعزلًا: النوم أول ما يختل في معظم الاضطرابات النفسية، وآخر ما يتعافى بعد السحب."),
    ("traitement de la cause, restructuration des horaires, thérapie de l'insomnie, sevrage progressif des somnifères déjà installés.",
     "treating the cause, restructuring hours, insomnia therapy, a gradual taper off sleeping pills already in place.",
     "علاج السبب، وإعادة ترتيب المواعيد، وعلاج الأرق، وخفض تدريجي للمنوّمات القائمة."),
    ("Troubles de la personnalité", "Personality disorders", "اضطرابات الشخصية"),
    ("Un fonctionnement stable et durable qui met en difficulté : instabilité émotionnelle et peur de l'abandon dans l'état-limite, évitement des relations, dépendance, rigidité. Les conduites addictives et les passages à l'acte y sont fréquents.",
     "A stable, lasting way of functioning that causes difficulty: emotional instability and fear of abandonment in borderline states, avoidance of relationships, dependence, rigidity. Addictive behaviour and acting out are frequent.",
     "نمط أداء ثابت وطويل الأمد يسبّب صعوبات: تقلّب انفعالي وخوف من الهجر في الحالة الحدّية، وتجنّب للعلاقات، واعتمادية، وجمود. السلوكيات الإدمانية والتصرفات الاندفاعية شائعة."),
    ("psychothérapie structurée dans la durée, travail sur la régulation des émotions, cadre clair et constant. Le séjour hospitalier sert aux périodes de crise, pas au traitement de fond.",
     "structured psychotherapy over time, work on emotion regulation, a clear and constant frame. Inpatient stays are for crisis periods, not for the underlying treatment.",
     "علاج نفسي منظَّم على المدى الطويل، وعمل على تنظيم الانفعالات، وإطار واضح وثابت. الإقامة في المستشفى لفترات الأزمة، لا للعلاج الأساسي."),
    ("Burn-out et épuisement", "Burnout and exhaustion", "الاحتراق النفسي والإنهاك"),
    ("Épuisement qui ne se répare plus au repos, distance cynique vis-à-vis du travail, sentiment d'inefficacité, puis souvent effondrement brutal. Fréquemment accompagné d'une augmentation discrète de la consommation d'alcool ou de somnifères.",
     "Exhaustion that rest no longer repairs, cynical distance from work, a sense of ineffectiveness, then often a sudden collapse. Frequently accompanied by a quiet increase in alcohol or sleeping-pill use.",
     "إنهاك لم تعد الراحة تصلحه، ومسافة ساخرة من العمل، وشعور بعدم الجدوى، ثم انهيار مفاجئ غالبًا. يرافقه كثيرًا ازدياد صامت في استهلاك الكحول أو المنوّمات."),
    ("arrêt et mise à distance, traitement d'un éventuel épisode dépressif, travail sur le retour — le retour au travail se prépare, il ne s'improvise pas.",
     "stopping and stepping back, treating any depressive episode, work on the return — going back to work is prepared, not improvised.",
     "توقف وابتعاد، وعلاج أي نوبة اكتئابية، وعمل على العودة — فالعودة إلى العمل تُحضَّر ولا تُرتجل."),

    # ── thérapies ───────────────────────────────────────────────────────
    ("Ce qu'on fait des journées.", "What the days are made of.", "ممّ تتكوّن الأيام."),
    ("Le traitement médicamenteux tient une place, pas toute la place. Le reste se joue en entretien, en groupe et dans le rythme.",
     "Medication has a place, not the whole place. The rest happens in sessions, in groups, and in the rhythm of the day.",
     "للدواء موضع، لا كل الموضع. أما البقية فتجري في الجلسات والمجموعات وفي إيقاع اليوم."),
    ("Entretien motivationnel", "Motivational interviewing", "المقابلة التحفيزية"),
    ("Faire émerger les raisons propres du patient plutôt que lui opposer les nôtres. C'est l'approche qui obtient le plus d'adhésion en addictologie.",
     "Drawing out the patient's own reasons rather than opposing them with ours. It is the approach that earns the most engagement in addiction medicine.",
     "استخراج أسباب المريض هو، بدل مواجهته بأسبابنا. وهو النهج الأكثر كسبًا للالتزام في طب الإدمان."),
    ("Thérapie cognitivo-comportementale", "Cognitive behavioural therapy", "العلاج المعرفي السلوكي"),
    ("Repérer les pensées et les situations qui précèdent la consommation ou la crise, et construire une autre réponse, à l'avance et par écrit.",
     "Identifying the thoughts and situations that come before use or crisis, and building a different response, in advance and in writing.",
     "تحديد الأفكار والمواقف التي تسبق الاستهلاك أو الأزمة، وبناء استجابة أخرى، مسبقًا وكتابةً."),
    ("Groupe de parole", "Group therapy", "مجموعة الحديث"),
    ("Entendre quelqu'un décrire exactement ce qu'on croyait être seul à vivre. C'est souvent le moment où la honte baisse assez pour que le travail commence.",
     "Hearing someone describe exactly what you thought you alone were living. It is often the moment shame drops enough for the work to begin.",
     "أن تسمع شخصًا يصف تمامًا ما ظننت أنك وحدك تعيشه. غالبًا هي اللحظة التي ينخفض فيها العار بما يكفي ليبدأ العمل."),
    ("Entretien familial", "Family session", "الجلسة العائلية"),
    ("L'entourage est épuisé, en colère, ou trop protecteur. On lui explique la maladie, ce qui aide et ce qui aggrave, et ce qu'il a le droit de ne plus porter.",
     "Families are exhausted, angry, or over-protective. We explain the illness, what helps and what makes it worse, and what they are allowed to stop carrying.",
     "المحيطون منهكون أو غاضبون أو مفرطون في الحماية. نشرح لهم المرض، وما يساعد وما يفاقم، وما يحقّ لهم التوقف عن حمله."),
    ("Psychoéducation", "Psychoeducation", "التثقيف النفسي"),
    ("Connaître son trouble, ses signes précoces, l'effet réel de son traitement. Un patient informé rechute moins et revient plus tôt.",
     "Knowing your disorder, its early signs, what your treatment actually does. An informed patient relapses less and comes back sooner.",
     "أن تعرف اضطرابك وعلاماته المبكرة والأثر الحقيقي لعلاجك. المريض المطّلع ينتكس أقل ويعود أبكر."),
    ("Art-thérapie", "Art therapy", "العلاج بالفن"),
    ("Peinture, écriture, musique, pour les moments où les mots ne viennent pas encore — fréquents dans les premiers jours d'un sevrage.",
     "Painting, writing, music, for the moments when words do not come yet — common in the first days of a withdrawal.",
     "رسم وكتابة وموسيقى، للحظات التي لا تأتي فيها الكلمات بعد — وهي كثيرة في أيام السحب الأولى."),
    ("Relaxation et activité physique", "Relaxation and physical activity", "الاسترخاء والنشاط البدني"),
    ("Respiration, relaxation, marche, remise en mouvement. Agit sur l'anxiété, le sommeil et le craving, sans interaction médicamenteuse.",
     "Breathing, relaxation, walking, getting moving again. It acts on anxiety, sleep and craving, with no drug interactions.",
     "تنفّس واسترخاء ومشي وعودة إلى الحركة. يؤثر في القلق والنوم والاشتهاء، دون تداخل دوائي."),
    ("Suivi nutritionnel", "Nutritional follow-up", "المتابعة الغذائية"),
    ("Renutrition et correction des carences après un sevrage alcoolique, encadrement des variations de poids liées aux traitements.",
     "Renutrition and correction of deficiencies after alcohol withdrawal, management of weight changes caused by medication.",
     "إعادة تغذية وتصحيح نقص العناصر بعد السحب الكحولي، وضبط تغيّرات الوزن الناتجة عن الأدوية."),

    # ── quand consulter ─────────────────────────────────────────────────
    ("À quel moment appeler.", "When to make the call.", "متى تُجري الاتصال."),
    ("On attend presque toujours trop longtemps — par honte, ou parce qu'on se dit qu'on gère. Un seul de ces signes suffit pour justifier un appel, et l'appel n'engage à rien.",
     "People almost always wait too long — out of shame, or because they tell themselves they have it under control. One of these signs is enough to justify a call, and the call commits you to nothing.",
     "ننتظر دائمًا أكثر من اللازم — خجلًا، أو لأننا نقول لأنفسنا إننا مسيطرون. علامة واحدة من هذه تكفي لتبرير اتصال، والاتصال لا يُلزمك بشيء."),
    ("Il faut boire ou consommer le matin pour que la journée démarre.",
     "You need a drink or a dose in the morning for the day to start.",
     "تحتاج إلى شراب أو جرعة في الصباح كي يبدأ اليوم."),
    ("Des tremblements, des sueurs ou de l'angoisse dès que l'on arrête.",
     "Tremor, sweating or dread as soon as you stop.",
     "رعشة أو تعرّق أو قلق بمجرد التوقف."),
    ("Les tentatives d'arrêt seul ont déjà échoué, plusieurs fois.",
     "Attempts to stop alone have already failed, more than once.",
     "محاولات التوقف وحدك فشلت بالفعل، أكثر من مرة."),
    ("Les doses augmentent, ou les somnifères ne suffisent plus.",
     "The doses are climbing, or the sleeping pills no longer work.",
     "الجرعات ترتفع، أو المنوّمات لم تعد تكفي."),
    ("Le travail, l'argent ou la famille commencent à en payer le prix.",
     "Work, money or family are starting to pay the price.",
     "العمل أو المال أو العائلة بدأت تدفع الثمن."),
    ("Une tristesse ou une angoisse qui dure depuis plus de deux semaines.",
     "Sadness or dread that has lasted more than two weeks.",
     "حزن أو قلق مستمر منذ أكثر من أسبوعين."),
    ("Des nuits blanches répétées, ou un sommeil qui s'est inversé.",
     "Repeated sleepless nights, or sleep that has flipped around.",
     "ليالٍ بيضاء متكرّرة، أو نوم انقلب موعده."),
    ("Des propos étranges, de la méfiance inhabituelle, un retrait brutal.",
     "Strange talk, unusual suspicion, an abrupt withdrawal from everyone.",
     "كلام غريب، وارتياب غير معتاد، وانسحاب مفاجئ."),
    ("Des idées de mort, un scénario, ou un passage à l'acte évité de peu.",
     "Thoughts of death, a plan, or an attempt narrowly avoided.",
     "أفكار عن الموت، أو خطة، أو محاولة نجا منها بصعوبة."),

    # ── où ──────────────────────────────────────────────────────────────
    ("Où ces soins sont délivrés.", "Where this care is given.", "أين تُقدَّم هذه الرعاية."),
    ("À la Clinique Espoir, El Menzah 9 à Tunis, en hospitalisation complète, en hôpital de jour ou en consultation externe, selon ce que la situation demande. Chambres individuelles ou doubles, présence infirmière 24 h/24, transport médicalisé sur demande.",
     "At Clinique Espoir, El Menzah 9 in Tunis — as a full inpatient stay, in day hospital, or as an outpatient, according to what the situation calls for. Single or double rooms, nursing presence 24/7, medical transport on request.",
     "في عيادة الأمل، المنزه 9 بتونس — إقامة كاملة، أو مستشفى نهاري، أو استشارة خارجية، بحسب ما تقتضيه الحالة. غرف فردية أو مزدوجة، ووجود تمريضي على مدار الساعة، ونقل طبي عند الطلب."),
    ("Hall d'accueil clair de la clinique, plantes et comptoir.",
     "The clinic's bright reception hall, plants and a desk.",
     "بهو استقبال مضيء في العيادة، نباتات ومكتب."),
    ("Chambre individuelle claire.", "A bright single room.", "غرفة فردية مضيئة."),
    ("Salle de consultation, deux fauteuils face à face.",
     "A consulting room, two armchairs facing each other.",
     "غرفة استشارة، كرسيان متقابلان."),
    ("Les photographies de l'entrée et de la réception sont celles de la clinique. Les autres images illustrent l'aménagement des espaces.",
     "The photographs of the entrance and the reception are of the clinic itself. The other images illustrate how the spaces are arranged.",
     "صورتا المدخل والاستقبال هما للعيادة نفسها. أما بقية الصور فتوضّح طريقة تنظيم المساحات."),

    # ── questions ───────────────────────────────────────────────────────
    ("Les questions qu'on n'ose pas poser.", "The questions people don't dare ask.", "الأسئلة التي لا يجرؤ أحد على طرحها."),
    ("Peut-on faire un sevrage à la maison ?", "Can withdrawal be done at home?", "هل يمكن إجراء السحب في المنزل؟"),
    ("Pour le tabac ou le cannabis, souvent oui, avec un suivi. Pour l'alcool et les benzodiazépines, l'arrêt sans encadrement médical expose à des convulsions et à un delirium tremens : la décision se prend après examen, jamais à l'avance et jamais seul.",
     "For tobacco or cannabis, often yes, with follow-up. For alcohol and benzodiazepines, stopping without medical supervision exposes you to seizures and delirium tremens: the decision is made after examination, never in advance and never alone.",
     "بالنسبة للتبغ أو القنّب، نعم في الغالب، مع متابعة. أما الكحول والبنزوديازيبينات فالتوقف دون إشراف طبي يعرّض لنوبات تشنّجية وهذيان ارتعاشي: القرار يُتخذ بعد الفحص، لا مسبقًا ولا بمفردك."),
    ("Combien de temps dure une hospitalisation pour sevrage ?",
     "How long is an inpatient stay for withdrawal?",
     "كم تدوم الإقامة في المستشفى للسحب؟"),
    ("La phase aiguë dure en général une semaine. Un séjour de deux à quatre semaines permet en plus de stabiliser le sommeil, de traiter le trouble sous-jacent et d'engager le travail sur le craving. La durée est réévaluée chaque semaine avec le patient.",
     "The acute phase generally lasts a week. A stay of two to four weeks additionally allows sleep to stabilise, the underlying disorder to be treated, and the work on craving to begin. The duration is reviewed every week with the patient.",
     "تدوم المرحلة الحادة أسبوعًا عادة. أما إقامة من أسبوعين إلى أربعة فتتيح إضافةً إلى ذلك استقرار النوم، وعلاج الاضطراب الكامن، وبدء العمل على الاشتهاء. تُراجَع المدة أسبوعيًا مع المريض."),
    ("Et si la personne refuse de venir ?", "What if the person refuses to come?", "وماذا لو رفض الشخص المجيء؟"),
    ("C'est la situation la plus fréquente. Appelez d'abord pour vous : on vous aide à préparer la conversation, à choisir le moment, et à savoir quoi faire si l'état se dégrade. L'hospitalisation se fait en principe avec le consentement du patient ; lorsque l'état ne le permet pas, la loi encadre l'admission à la demande d'un proche et la procédure vous est expliquée.",
     "That is the most common situation. Call for yourself first: we help you prepare the conversation, choose the moment, and know what to do if things get worse. Admission is in principle with the patient's consent; where their state does not allow it, the law provides for admission at a relative's request, and the procedure is explained to you.",
     "هذه أكثر الحالات شيوعًا. اتصل من أجل نفسك أولًا: نساعدك على تحضير الحديث، واختيار اللحظة، ومعرفة ما تفعله إذا ساءت الحال. يتم الإدخال مبدئيًا بموافقة المريض؛ وحين لا تسمح حالته بذلك، ينظّم القانون الإدخال بطلب من أحد الأقارب، وتُشرَح لك الإجراءات."),
    ("La rechute, c'est l'échec du traitement ?", "Is relapse a failure of the treatment?", "هل الانتكاس فشل للعلاج؟"),
    ("Non. La rechute fait partie de l'histoire de la plupart des dépendances ; ce qui compte, c'est le délai avant de revenir. Revenir après trois jours de reprise n'a rien à voir avec revenir après six mois — et personne ici ne reproche l'un ou l'autre.",
     "No. Relapse is part of the story of most dependencies; what matters is how long before you come back. Coming back after three days of using is not the same as coming back after six months — and nobody here reproaches either one.",
     "لا. الانتكاس جزء من قصة معظم حالات الاعتماد؛ وما يهم هو المدة قبل العودة. العودة بعد ثلاثة أيام من الاستهلاك ليست كالعودة بعد ستة أشهر — ولا أحد هنا يلوم على أيٍّ منهما."),
    ("Est-ce que cela restera confidentiel ?", "Will this stay confidential?", "هل تبقى المعلومات سرّية؟"),
    ("Le secret médical couvre le séjour entier. Aucune information n'est transmise à un employeur, à une administration ou à un tiers sans l'accord écrit du patient.",
     "Medical confidentiality covers the whole stay. No information is passed to an employer, an administration or a third party without the patient's written consent.",
     "تغطي السرية الطبية الإقامة بكاملها. ولا تُنقل أي معلومة إلى صاحب عمل أو إدارة أو طرف ثالث دون موافقة خطية من المريض."),
    ("Quels sont les tarifs ?", "What does it cost?", "ما هي التكلفة؟"),
    ("Ils dépendent du type de prise en charge et de la chambre. Ils sont communiqués au téléphone, en détail et sans engagement, avant toute admission.",
     "It depends on the type of care and the room. Prices are given on the phone, in detail and without obligation, before any admission.",
     "تعتمد على نوع الرعاية والغرفة. تُبلَّغ الأسعار عبر الهاتف، بالتفصيل ودون التزام، قبل أي إدخال."),
    ("Les informations de cette page sont générales et ne remplacent pas une consultation médicale. Aucun traitement, aucun arrêt et aucune modification de dose ne doit être décidé à partir de ce site.",
     "The information on this page is general and does not replace a medical consultation. No treatment, no cessation and no dose change should be decided on the basis of this site.",
     "المعلومات في هذه الصفحة عامة ولا تُغني عن استشارة طبية. لا ينبغي اتخاذ أي قرار بعلاج أو بتوقف أو بتغيير جرعة استنادًا إلى هذا الموقع."),

    # ── contact ─────────────────────────────────────────────────────────
    ("Décrivez la situation. On vous dit quoi faire.",
     "Describe the situation. We'll tell you what to do.",
     "صِف الحالة. ونقول لك ما العمل."),
    ("24 h/24, 7 j/7", "24/7", "24 ساعة، 7 أيام"),
    ("Réponse sous 24 heures · lettres d'admission des confrères",
     "Reply within 24 hours · referral letters from colleagues",
     "رد خلال 24 ساعة · رسائل إحالة من الزملاء"),
    ("Clinique Espoir — El Menzah 9, Tunis", "Clinique Espoir — El Menzah 9, Tunis", "عيادة الأمل — المنزه 9، تونس"),
    ("Consultations : lun–ven 8 h–18 h · sam 8 h–13 h",
     "Consultations: Mon–Fri 8 a.m.–6 p.m. · Sat 8 a.m.–1 p.m.",
     "الاستشارات: الاثنين–الجمعة 8–18 · السبت 8–13"),
    ("Plan d'accès — El Menzah 9, Tunis", "Map — El Menzah 9, Tunis", "خريطة — المنزه 9، تونس"),
    ("Votre nom", "Your name", "اسمك"),
    ("Téléphone", "Phone", "الهاتف"),
    ("E-mail", "Email", "البريد الإلكتروني"),
    ("Votre demande", "Your request", "طلبك"),
    ("Sevrage — alcool", "Withdrawal — alcohol", "سحب — كحول"),
    ("Sevrage — benzodiazépines ou somnifères", "Withdrawal — benzodiazepines or sleeping pills", "سحب — بنزوديازيبينات أو منوّمات"),
    ("Sevrage — opiacés", "Withdrawal — opioids", "سحب — مواد أفيونية"),
    ("Sevrage — cannabis, cocaïne ou stimulants", "Withdrawal — cannabis, cocaine or stimulants", "سحب — قنّب أو كوكايين أو منشّطات"),
    ("Addiction sans produit (jeu, écrans)", "Behavioural addiction (gambling, screens)", "إدمان سلوكي (قمار، شاشات)"),
    ("Trouble psychiatrique — consultation", "Psychiatric disorder — consultation", "اضطراب نفسي — استشارة"),
    ("Urgence — besoin d'une réponse aujourd'hui", "Emergency — I need an answer today", "طارئ — أحتاج ردًّا اليوم"),
    ("Lettre d'admission (médecin)", "Referral letter (doctor)", "رسالة إحالة (طبيب)"),
    ("Ce qui se passe", "What is happening", "ما الذي يحدث"),
    ("Depuis quand, quelles quantités, ce qui vous inquiète. Quelques lignes suffisent.",
     "How long, what quantities, what worries you. A few lines are enough.",
     "منذ متى، وبأي كميات، وما الذي يقلقك. بضعة أسطر تكفي."),
    ("J'accepte d'être recontacté à propos de cette demande.",
     "I agree to be contacted about this request.",
     "أوافق على أن يتم الاتصال بي بخصوص هذا الطلب."),
    ("Envoyer la demande", "Send the request", "أرسل الطلب"),
    ("Vos informations ne servent qu'à vous rappeler. Aucun dossier médical ne transite par ce formulaire.",
     "Your details are used only to call you back. No medical records travel through this form.",
     "تُستخدم بياناتك للاتصال بك فقط. ولا تمر أي سجلات طبية عبر هذا النموذج."),

    # ── pied de page ────────────────────────────────────────────────────
    ("Sevrage et soins psychiatriques", "Withdrawal and psychiatric care", "علاج الانسحاب والرعاية النفسية"),
    ("Pied de page", "Footer", "تذييل الصفحة"),
    ("Le protocole", "The protocol", "البروتوكول"),
    ("Les troubles", "The disorders", "الاضطرابات"),
    ("Le manque", "Withdrawal", "الانسحاب"),
    ("Urgence vitale : 190 (SAMU)", "Life-threatening emergency: 190", "طوارئ تهدّد الحياة: 190"),
    ("© 2026 Clinique psychiatrique Espoir — El Menzah 9.",
     "© 2026 Clinique psychiatrique Espoir — El Menzah 9.",
     "© 2026 عيادة الأمل النفسية — المنزه 9."),
    ("Contenu informatif, à valider par la direction médicale avant mise en ligne.",
     "Informational content, to be validated by the medical director before going live.",
     "محتوى إعلامي، يخضع لمصادقة الإدارة الطبية قبل النشر."),
    ("Appeler la clinique", "Call the clinic", "اتصل بالعيادة"),
    ("Appeler — 24 h/24", "Call — 24/7", "اتصل — 24/24"),
    ("Aller au formulaire de contact", "Go to the contact form", "انتقل إلى نموذج الاتصال"),
]

HEAD_ATTRS = {
    "en": [('<html lang="fr">', '<html lang="en">'),
           ('content="fr_TN"', 'content="en_US"')],
    "ar": [('<html lang="fr">', '<html lang="ar" dir="rtl">'),
           ('content="fr_TN"', 'content="ar_TN"')],
}


def pattern_for(fr):
    """Une espace dans la clé accepte un retour à la ligne, une indentation
    ou une espace insécable typographique (&nbsp;) dans le source."""
    return r"(?:\s|&nbsp;)+".join(re.escape(t) for t in fr.split(" ") if t)


def build(lang, idx):
    src = SRC.read_text()
    pairs = sorted(T, key=lambda r: -len(r[0]))
    tokens = {}
    misses = 0
    for i, row in enumerate(pairs):
        fr, target = row[0], row[idx]
        tok = f"\x00{i}\x00"
        src, n = re.subn(pattern_for(fr), tok.replace("\\", "\\\\"), src)
        if n == 0:
            misses += 1
            print(f"  · introuvable, ignoré : {fr[:56]}…", file=sys.stderr)
        tokens[tok] = target
    for tok, target in tokens.items():
        src = src.replace(tok, target)
    if misses:
        print(f"  ({misses} chaîne(s) non trouvée(s))", file=sys.stderr)

    for a, b in HEAD_ATTRS[lang]:
        src = src.replace(a, b)

    # canonique et og:url propres à la langue
    src = src.replace('<link rel="canonical" href="https://sevrage-tunisie.com/">',
                      f'<link rel="canonical" href="https://sevrage-tunisie.com/{lang}.html">')
    src = src.replace('<meta property="og:url" content="https://sevrage-tunisie.com/">',
                      f'<meta property="og:url" content="https://sevrage-tunisie.com/{lang}.html">')

    # lien FR du tiroir mobile : absent de index.html (page FR courante),
    # on l'injecte pour que le français reste joignable depuis ar/en
    src = src.replace(
        '<a href="ar.html" hreflang="ar" lang="ar">العربية</a>',
        '<a href="index.html" hreflang="fr" lang="fr">Français</a>\n'
        '    <a href="ar.html" hreflang="ar" lang="ar">العربية</a>')

    # l'onglet de langue actif (retirer aussi l'aria-current nu du lien FR)
    src = (src.replace(' class="is-on" aria-current="page"', "")
              .replace(' aria-current="page"', "")
              .replace(' class="is-on"', ""))
    src = re.sub(rf'(<a href="{ "index" if lang == "fr" else lang }\.html" hreflang="{lang}"[^>]*?)>',
                 r'\1 class="is-on" aria-current="page">', src)

    out = SRC.parent / f"{lang}.html"
    out.write_text(src)
    print(f"{out.name} écrit ({len(src) // 1024} Ko)")


if __name__ == "__main__":
    print("en.html")
    build("en", 1)
    print("ar.html")
    build("ar", 2)
